[package]
name = "foundations"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/foundations"

[lib]
name = "foundations"
path = "lib.rs"

[features]
concat-string = []
error-enum = []
byterepr = []
kvdump = ["blake3"]
key-index = []
key-index-map = ["key-index"]
default = ["concat-string", "error-enum", "byterepr", "kvdump", "key-index", "key-index-map"]

[dependencies]
blake3 = { version = "1", optional = true }
