[package]
name = "foundations"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/foundations"

[lib]
name = "foundations"
path = "lib.rs"

[dependencies]
blake3 = { version = "1", optional = true }
tiny-keccak = { version = "2", features = ["sha3", "shake"], optional = true }

[features]
now = []
usize-casting = []
byterepr = []
bytes-read = []
num-compress = []
case-convert = []
const-bytes-equal = []
key-index = []
key-index-map = ["key-index"]
sha3 = ["tiny-keccak"]
kvdump = ["usize-casting", "blake3"]

concat-string = []
error-enum = []
num-enum = []
byterepr-macros = ["byterepr"]

default = [
    "now",
    "usize-casting",
    "byterepr",
    "bytes-read",
    "num-compress",
    "case-convert",
    "const-bytes-equal",
    "key-index",
    "key-index-map",
    "sha3",
    "kvdump",

    "concat-string",
    "error-enum",
    "num-enum",
    "byterepr-macros",
]
