[package]
name = "foundations"
version = "0.1.0"
edition = "2021"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/foundations"

[lib]
name = "foundations"
path = "lib.rs"
